version: '3.1'

services:
  # Service de base de donnée mysql
  db:
    image: mariadb:10.3
    restart: always
    environment:      
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
    volumes:
      - dbvolume:/var/lib/mysql
    networks:
      - network
    ports:
      - 5412-5999:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - db
    ports:
      - 7000:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - network

  php:
    build: ./
    links:
      - db
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    networks:
      - network
      
networks:
  network:
    driver: bridge

volumes:
  dbvolume:
